@startuml
title API REST
hide footbox
skinparam monochrome true
skinparam sequenceMessageAlign center
/'skinparam ParticipantPadding 100'/

participant "HTTP Client" as client
participant "HTTP Server" as server

client -> server: Request HTTP\n(GET, POST, PUT, DELETE)
activate server
server -> client: \nResponse HTTP\n(JSON, XML)
deactivate server
client -> server: \nGET /api/v1/resource
activate server
note right: GET /api/v1/resource HTTP/1.1\nHost: https://exemplo.api.com/
server -> client: \nJSON
deactivate server
note left: HTTP/1.1 200 OK\n\n{"key1": "value2", "key2": "value2"}
@enduml
