@baseUrl = http://localhost:3000

### Estado do servico
GET {{baseUrl}}/health

### Listar as tarefas
GET {{baseUrl}}/tasks

### Buscar uma tarefa
GET {{baseUrl}}/tasks/1

### Buscar com id nao inteiro
GET {{baseUrl}}/tasks/abc

### Criar uma tarefa
POST {{baseUrl}}/tasks
Content-Type: application/json

{
  "title": "Migrar a API para TypeScript"
}

### Criar com Content-Type errado, recusado pelo requireJson
POST {{baseUrl}}/tasks
Content-Type: text/plain

titulo qualquer

### Atualizar uma tarefa
PUT {{baseUrl}}/tasks/1
Content-Type: application/json

{
  "done": false
}

### Remover uma tarefa
DELETE {{baseUrl}}/tasks/2
