services:

  cassandra:
    container_name: cassandra
    image: cassandra:4.1
    restart: always
    environment:
      - CASSANDRA_CLUSTER_NAME=devlab_cluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=128M
    networks:
      - app-tier
    ports:
      - 9042:9042 # Native CQL transport
    volumes:
      - cassandra_data:/var/lib/cassandra

volumes:
  cassandra_data:

networks:
  app-tier:
    driver: bridge
