# @host = https://xyz.supabase.co
@host = {{$dotenv SUPABASE_URL}}
@token = {{$dotenv SUPABASE_KEY}}

### Create a investment
# @name createInvestment
POST {{host}}/rest/v1/investments
apikey: {{token}}
Authorization: Bearer {{token}}
Content-Type: application/json
Prefer: return=representation

{
  "name": "Tesouro Selic 2029",
  "value": 10000,
  "origin": "Tesouro Direto",
  "category": "Pós",
  "interest": "100% Selic"
}
