services:

  neo4j:
    container_name: neo4j
    image: neo4j:5.18-community
    restart: always
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS=["apoc"]
    networks:
      - app-tier
    ports:
      - 7474:7474 # HTTP / Neo4j Browser
      - 7687:7687 # Bolt protocol
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

volumes:
  neo4j_data:
  neo4j_logs:

networks:
  app-tier:
    driver: bridge
