@host = http://localhost:3000/api
@createdHostId = {{createdHost.response.body.$.id}}

### Create Host

# @name createdHost
POST {{host}}/hosts
Content-Type: application/json

{
  "name": "Google DNS",
  "address": "8.8.8.8"
}

### Create Host without address

POST {{host}}/hosts
Content-Type: application/json

{
  "name": "Google DNS"
}

### Create Host without body

POST {{host}}/hosts

### Read Hosts

GET {{host}}/hosts

### Read Hosts by id

GET {{host}}/hosts/{{createdHostId}}

### Read Hosts by invalid id

GET {{host}}/hosts/a

### Read Hosts by name

GET {{host}}/hosts?name=Google

### Update Host

PUT {{host}}/hosts/{{createdHostId}}
Content-Type: application/json

{
  "name": "Google Public DNS",
  "address": "8.8.4.4"
}

### Update Host without address

PUT {{host}}/hosts/{{createdHostId}}
Content-Type: application/json

{
  "name": "Google Public DNS"
}

### Update Host with invalid id

PUT {{host}}/hosts/a
Content-Type: application/json

{
  "name": "Google Public DNS",
  "address": "8.8.4.4"
}

### Delete Host

DELETE {{host}}/hosts/{{createdHostId}}

### Delete Host with invalid id

DELETE {{host}}/hosts/a
