@server = http://localhost:3000

### Lista os usuarios
GET {{server}}/users

### Busca um usuario
GET {{server}}/users/1

### Cria um usuario
# @name createUser
POST {{server}}/users
Content-Type: application/json

{
  "name": "Carla",
  "email": "carla@example.com"
}

### Cria um usuario sem email (400)
POST {{server}}/users
Content-Type: application/json

{
  "name": "Sem e-mail"
}

### E-mail duplicado (409)
POST {{server}}/users
Content-Type: application/json

{
  "name": "Ana de novo",
  "email": "ana@example.com"
}

### Atualiza um usuario
PUT {{server}}/users/{{createUser.response.body.$.id}}
Content-Type: application/json

{
  "name": "Carla Souza"
}

### Remove um usuario
DELETE {{server}}/users/{{createUser.response.body.$.id}}

### Rota inexistente (404)
GET {{server}}/nao-existe
