@host = {{$dotenv SUPABASE_URL}}
@token = {{$dotenv SUPABASE_KEY}}
@createdInvestmentId = {{createInvestment.response.body.$[0].id}}

### Update a investment
PATCH  {{host}}/rest/v1/investments?id=eq.{{createdInvestmentId}}
apikey: {{token}}
Authorization: Bearer {{token}}
Content-Type: application/json
Prefer: return=representation

{
  "value": 15000
}
