@host = http://localhost:3000

### Cotação de um ativo
GET {{host}}/api/quote?symbol=PETR4

### Parâmetro ausente devolve 400
GET {{host}}/api/quote

### Método não suportado devolve 405
POST {{host}}/api/quote?symbol=PETR4
