@host = http://localhost:3000/api
@createdHostId = {{createdHost.response.body.$.id}}

### Create Host

# @name createdHost
POST {{host}}/hosts
Content-Type: application/json

{
  "name": "Google DNS",
  "address": "8.8.8.8",
  "tags": ["infra", "dns"]
}

### Create Host without address

POST {{host}}/hosts
Content-Type: application/json

{
  "name": "Google DNS"
}

### Create Host without body

POST {{host}}/hosts

### Read Hosts

GET {{host}}/hosts

### Read Hosts by id

GET {{host}}/hosts/{{createdHostId}}

### Read Hosts by invalid id

GET {{host}}/hosts/a

### Read Hosts by name

GET {{host}}/hosts?name=Google

### Update Host

PUT {{host}}/hosts/{{createdHostId}}
Content-Type: application/json

{
  "name": "Google Public DNS",
  "address": "8.8.4.4",
  "tags": ["infra"]
}

### Update Host without address

PUT {{host}}/hosts/{{createdHostId}}
Content-Type: application/json

{
  "name": "Google Public DNS"
}

### Update Host with invalid id

PUT {{host}}/hosts/a
Content-Type: application/json

{
  "name": "Google Public DNS",
  "address": "8.8.4.4",
  "tags": ["infra"]
}

### Delete Host

DELETE {{host}}/hosts/{{createdHostId}}

### Delete Host with invalid id

DELETE {{host}}/hosts/a

### Read Hosts by tag

GET {{host}}/hosts?tag=infra

### Read Ping history of a Host

GET {{host}}/hosts/{{createdHostId}}/pings

### Read Ping history of an unknown Host

GET {{host}}/hosts/00000000-0000-4000-8000-000000000000/pings

### Run a Ping now

POST {{host}}/hosts/{{createdHostId}}/pings

### Run a Ping on an unknown Host

POST {{host}}/hosts/00000000-0000-4000-8000-000000000000/pings

### Read Tags

GET {{host}}/tags

### Create Tag

POST {{host}}/tags
Content-Type: application/json

{
  "name": "backup",
  "color": "#8b5cf6"
}

### Create Tag with duplicated name

POST {{host}}/tags
Content-Type: application/json

{
  "name": "backup",
  "color": "#8b5cf6"
}

### Create User

POST {{host}}/users
Content-Type: application/json

{
  "name": "Ana Souza",
  "email": "ana@exemplo.com",
  "password": "senha-secreta",
  "confirmationPassword": "senha-secreta"
}

### Create User with duplicated email

POST {{host}}/users
Content-Type: application/json

{
  "name": "Ana Souza",
  "email": "ana@exemplo.com",
  "password": "senha-secreta",
  "confirmationPassword": "senha-secreta"
}

### Create User with mismatched confirmation

POST {{host}}/users
Content-Type: application/json

{
  "name": "Ana Souza",
  "email": "outra@exemplo.com",
  "password": "senha-secreta",
  "confirmationPassword": "senha-errada"
}
