@baseUrl = http://localhost:3000

### Estado do servico
GET {{baseUrl}}/health

### Listar as tarefas
GET {{baseUrl}}/tasks

### Buscar uma tarefa
GET {{baseUrl}}/tasks/1

### Buscar uma tarefa inexistente
GET {{baseUrl}}/tasks/99

### Criar uma tarefa
POST {{baseUrl}}/tasks
Content-Type: application/json

{
  "title": "Separar model, controller e router"
}

### Atualizar uma tarefa
PUT {{baseUrl}}/tasks/1
Content-Type: application/json

{
  "done": false
}

### Remover uma tarefa
DELETE {{baseUrl}}/tasks/2

### Rota inexistente, tratada pelo notFound
GET {{baseUrl}}/nada
