@host = http://localhost:3000/api
@token = {{signin.response.body.$.token}}
@createdHostId = {{createdHost.response.body.$.id}}

### Signin

# @name signin
POST {{host}}/signin
Content-Type: application/json

{
  "email": "ana@exemplo.com",
  "password": "senha-secreta"
}

### Signin with wrong password

POST {{host}}/signin
Content-Type: application/json

{
  "email": "ana@exemplo.com",
  "password": "senha-errada"
}

### Create User

POST {{host}}/users
Content-Type: application/json

{
  "name": "Bruno Lima",
  "email": "bruno@exemplo.com",
  "password": "senha-secreta",
  "confirmationPassword": "senha-secreta"
}

### Create User with duplicated email

POST {{host}}/users
Content-Type: application/json

{
  "name": "Bruno Lima",
  "email": "bruno@exemplo.com",
  "password": "senha-secreta",
  "confirmationPassword": "senha-secreta"
}

### Create Host

# @name createdHost
POST {{host}}/hosts
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Google DNS",
  "address": "8.8.8.8",
  "tags": ["infra", "dns"]
}

### Create Host without address

POST {{host}}/hosts
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Google DNS"
}

### Read Hosts

GET {{host}}/hosts
Authorization: Bearer {{token}}

### Read Hosts by name

GET {{host}}/hosts?name=Google
Authorization: Bearer {{token}}

### Read Hosts by tag

GET {{host}}/hosts?tag=infra
Authorization: Bearer {{token}}

### Read Hosts by id

GET {{host}}/hosts/{{createdHostId}}
Authorization: Bearer {{token}}

### Read Hosts by invalid id

GET {{host}}/hosts/a
Authorization: Bearer {{token}}

### Update Host

PUT {{host}}/hosts/{{createdHostId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Google Public DNS",
  "address": "8.8.4.4",
  "tags": ["infra"]
}

### Read Ping history of a Host

GET {{host}}/hosts/{{createdHostId}}/pings
Authorization: Bearer {{token}}

### Run a Ping now

POST {{host}}/hosts/{{createdHostId}}/pings
Authorization: Bearer {{token}}

### Read Tags

GET {{host}}/tags
Authorization: Bearer {{token}}

### Create Tag

POST {{host}}/tags
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "backup",
  "color": "#8b5cf6"
}

### Delete Host

DELETE {{host}}/hosts/{{createdHostId}}
Authorization: Bearer {{token}}

### Read Hosts without token

GET {{host}}/hosts

### Read Hosts with a tampered token

GET {{host}}/hosts
Authorization: Bearer {{token}}x

### Read a Host of another owner

GET {{host}}/hosts/00000000-0000-4000-8000-000000000000
Authorization: Bearer {{token}}
