@baseUrl = http://localhost:3000

### Estado do servico
GET {{baseUrl}}/health

### Listar as tarefas
GET {{baseUrl}}/tasks

### Buscar uma tarefa pelo parametro de rota
GET {{baseUrl}}/tasks/1

### Buscar uma tarefa inexistente
GET {{baseUrl}}/tasks/99

### Criar uma tarefa com corpo JSON
POST {{baseUrl}}/tasks
Content-Type: application/json

{
  "title": "Ler a documentacao do Express"
}

### Criar uma tarefa sem o campo obrigatorio
POST {{baseUrl}}/tasks
Content-Type: application/json

{}
